logging.level:
  tech.blackfall.dicedist: DEBUG
  org.zalando.logbook: TRACE

spring:
  application:
    name: dice-distribution
  datasource:
    url: jdbc:postgresql://localhost:5432/dicedist
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, logging

logbook:
  exclude:
    - /actuator/health/*
    - /actuator/health
    - /v3/api-docs
    - /v3/api-docs/*
    - /swagger-ui.html
    - /swagger-ui/*
  format:
    style: http

