### Default invocation
GET http://localhost:8080/v1/simulation

### Miminal result
GET http://localhost:8080/v1/simulation?dice=1&sides=4&rolls=1

### Should return validation errors
GET http://localhost:8080/v1/simulation?dice=-10&sides=0&rolls=0

### Should use default number of dice
GET http://localhost:8080/v1/simulation?sides=6&rolls=2

### Large concurrent query
GET http://localhost:8080/v1/simulation?dice=10&rolls=10000000&mode=conc

### Large iterative query
GET http://localhost:8080/v1/simulation?dice=10&rolls=10000000&mode=iter
